import classNames from 'classnames';
import './globals.css';
import { Aleo } from 'next/font/google';
import PropTypes from 'prop-types';

const aleo = Aleo({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={classNames(
          'bg-bg text-lg text-dark font-medium',
          aleo.className
        )}
      >
        {children}
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.any,
};
