import classNames from 'classnames';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classNames('bg-bg min-h-screen h-screen')}>
        {children}
      </body>
    </html>
  );
}
